import React from 'react'
import './periodicTable.css'

const PeriodicLists = () => (
  <div class="periodic-table-wrapper">
    <div class="periodic-table">
      <a
        class="periodic-element"
        target="_blank"
        rel="noopener noreferrer"
        href="https://reactjs.org/"
      >
        <svg
          width="100"
          height="100"
          viewBox="0 0 100 100"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <text
            class="periodic-element-stars"
            x="10"
            y="20"
            font-size="14"
            fill="white"
          >
            Library
          </text>
          <text
            class="periodic-element-symbol"
            x="50"
            y="60"
            width="100%"
            text-anchor="middle"
            font-size="24"
            fill="#72D7D1"
          >
            R
          </text>
          <text
            class="periodic-element-name"
            x="50"
            y="80"
            font-size="14"
            fill="#72D7D1"
            text-anchor="middle"
          >
            React
          </text>
        </svg>
      </a>
      <a
        class="periodic-element"
        target="_blank"
        href="https://firebase.google.com/"
        rel="noopener noreferrer"
      >
        <svg
          width="100"
          height="100"
          viewBox="0 0 100 100"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <text
            class="periodic-element-stars"
            x="10"
            y="20"
            font-size="14"
            fill="white"
          >
            Database
          </text>
          <text
            class="periodic-element-symbol"
            x="50"
            y="60"
            width="100%"
            text-anchor="middle"
            font-size="24"
            fill="#F7DF1E"
          >
            Fb
          </text>
          <text
            class="periodic-element-name"
            x="50"
            y="80"
            font-size="14"
            fill="#F7DF1E"
            text-anchor="middle"
          >
            Firebase
          </text>
        </svg>
      </a>
      <a
        class="periodic-element"
        target="_blank"
        rel="noopener noreferrer"
        href="https://bitbucket.org"
      >
        <svg
          width="100"
          height="100"
          viewBox="0 0 100 100"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <text
            class="periodic-element-stars"
            x="10"
            y="20"
            font-size="14"
            fill="white"
          >
            Source
          </text>
          <text
            class="periodic-element-symbol"
            x="50"
            y="60"
            width="100%"
            text-anchor="middle"
            font-size="24"
            fill="#7FD258"
          >
            Bb
          </text>
          <text
            class="periodic-element-name"
            x="50"
            y="80"
            font-size="14"
            fill="#7FD258"
            text-anchor="middle"
          >
            Bitbucket
          </text>
        </svg>
      </a>
      <a
        class="periodic-element"
        target="_blank"
        rel="noopener noreferrer"
        href="https://www.netlify.com/"
      >
        <svg
          width="100"
          height="100"
          viewBox="0 0 100 100"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <text
            class="periodic-element-stars"
            x="10"
            y="20"
            font-size="14"
            fill="white"
          >
            Hosting
          </text>
          <text
            class="periodic-element-symbol"
            x="50"
            y="60"
            width="100%"
            text-anchor="middle"
            font-size="24"
            fill="#9D7CE2"
          >
            Nl
          </text>
          <text
            class="periodic-element-name"
            x="50"
            y="80"
            font-size="14"
            fill="#9D7CE2"
            text-anchor="middle"
          >
            Netlify
          </text>
        </svg>
      </a>
    </div>
  </div>
)

export default PeriodicLists
